---
Description: POC graphql aws lambda

Parameters:
  Version:
    Description: Application version number
    Type: String

  BucketName:
    Description: S3 bucket name where the lambda code lives
    Type: String

Resources:
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref BucketName
        S3Key: !Sub dist-${Version}.zip
      Handler: src/index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: nodejs12.x
      Timeout: 10
      Description: GraphQL Apollo Server

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: "LambdaFunctionPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
            - Effect: "Allow"
              Action:
              - logs: CreateLogGroup
              - logs: CreateLogStream
              - logs: PutLogEvents
              Resource: "*"

  GraphQLApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: apollo-graphql-api

  GraphQLApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt GraphQLApi.RootResourceId
      PathPart: !Ref GraphQLApi
      RestApiId: "searchzipcodes"

  GraphQLApiMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: POST
      ResourceId: !Ref GraphQLApi
      RestApiId: !Ref GraphQLApiResource
      AuthorizationType: None
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFunction.Arn}/invocations

  GraphQLApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:invokeFunction
      FunctionName: !GetAtt LambdaFunction.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:$${GraphQLApi}/*

  Outputs:
    ApiUrl:
      Description: Invoke url of API gateway endpoint
      Value: !Sub https://${GraphQLApi}.execute-api.${AWS::Region}.amazonaws.com/v1/searchzipcodes